apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game2048
  namespace: argocd
spec:
  project: game2048
  source:
    repoURL: https://github.com/GLPSravanaKumar/terraform_gitactn_eks_game2048.git
    targetRevision: main
    path: k8s/game2048
  destination:
    server: https://kubernetes.default.svc
    namespace: game-2048
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
