apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game2048
  namespace: argocd
spec:
  project: game2048
  source:
    repoURL: https://github.com/GLPSravanaKumar/terraform_gitactn_eks_game2048.git
    targetRevision: main
    path: .
  destination:
    server: https://23ED2B324FB69131599421A2E658564E.gr7.ap-south-1.eks.amazonaws.com
    namespace: game-2048
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      
